language: node_js
node_js:
  - '12.13'
script:
  - npm run build
  - npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: altay.aydemir@gmail.com
  api_key:
    secure: S2gBArDuLB2fpLlddDs2RYUgExJwhznnMSa15ynbxIqcuaJrn2YtwA1gaR1oct1tSOIvwyvxNmWa8f7+GqJ983RgKrR74lPBLDL9jMpqMKjmUsfAcVXX17VYeSDTCcpy6PaYFAJcJxy9Cgmhm8K2wi8lljOnjIRFg3PAw7/2PrF+0qUoa7GVyDeoH6K448AjyrmaLCmnm08U4IaBOv+r09T02VhHu5C51llwfTUSrvZW3KImWqRE7KYd1Dr1+G/hHslxsl5Oqkdka9Kj/WzVxK7vhWvQ+jjkQLWuPiE5nhDxk9RSrH+c06UCtQyyGxFirXgoCKz3sXgHG5dpfNVaaqOsxCCEqmzuc8rwOo2hKhk1Ps/8Zp7ANYCeQ5McoYs3VvaSuQATdb3lBrW/rE8ySXJtp3+lJFITtPp3sC/ZQoreUuR0uZ5FSazXFChPIwGbDyYq1ReninsFjWXPVktCeC6lylcKAt7IjU/LmHdVZLAO8/z8zGtnnQGJqC5eqX1zlszSh0sjaNsc9i+1B6JaGRyYrsSW2CcwaC/3nQFpEPjrXZjtCqxr7x62EjVzP4tziWyiIdt6MBfbgshGI3LAAHtGt87C+RA5Ap/mPEUglxtJFmCscHv229e78GN9cCY5LB8BinREgrXLejShAtNbk+uwTnGB+VOs47xx0KLQaS4=
  on:
    tags: true
    repo: putdotio/pas-js
