dist: trusty
language: node_js
node_js:
- '9'
script: npm run build
deploy:
  provider: npm
  email: altay.aydemir@gmail.com
  skip_cleanup: true
  api_key:
    secure: uH19JXCa3q5LVq6g8S45vH436hGeNm67AYj3g/iyO78lsUM0d4RYGg3+WUsmTQSUMDRnURoZusqAGLzIPRULndG0QFUaZnU2XqtkA/p5XLL8kEDlqJHItDTvuwOyDJf8BTUSJ7jQPfljT62kBq3kLzOcfPdyAuRjAAA3/KHkzRtC4Bh7XIPvBcngq4HJE2fUQvRHLXpADFdwcIU6aBWMnJ1pl3HEGkKsEV1/T0bTy0mroZLij3/xPWNdeGDknH/MjT6hZOsIdOziVPyUgBHmk5YR52lf3sYL+uoRFCTy4NkIFPBOlbcnrPvClsywvkvCuKqLAn0oXHpxLc4PgvWuJHKrHTx+xQFXBLiK3tamkq1hxXsrEiVq1ztPhnLLucXImt1dfkqgg2iRBX9HPTTCXTL6nfhgrkDzjpQTwmRitIq/KqQD4KE4cmLAfzjb9h+dcbrSSQKqghW2jxK1JavOOgsUWo8Ar5DLYxHL9/zWrPxCWjE7hZsHeRSlNAT7MIZmcqMW6TMt8jtZHWbTWANK1wkqn/D/5SpdXchxdRdxCVl9Z2onUJBjcUzAI095rmel8vo6sm/u57skQr38X2xkVI4hTDnSj9Ly8tyWxxBxmwXckGcTc/Jgs5RF0FofaDqqbV8qhHI0FAZKvdIl6SN+JxLmeglGAysq4HihD6p5JC8=
  on:
    tags: true
    repo: putdotio/pas-js
