language: node_js
node_js:
  - '12.13'
script:
  - npm run build
  - npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: altayhan.aydemir@gmail.com
  api_key:
    secure: 453sZoiIKd01YYDKrQ+7gaZUS5j1a2btKHnSIV1XoQeWLqZoXbhkPT0p9CNbk99Fruqrkhk82JC21KcPHI0wVMJhHdjfL43WNdjlc30ojmE1inHNknTP4DTgp6aVDtCHXifSD/jMQ8BKHqS4f8BNjqr07E3MxZsLAM0eHUYvX+7apJuEvA5qE8APJeAysu171tx5nVhmQfM6CotsZs5/vV7X03AqWuo0RNDusEvBQt298Kba3C0lgCSsd9CosthcUr4KqhzoOlZ6QxBjW+qHsW0ruxeoTwIMKJ51Rt1eToQc58qeacKXsTYHMCRBuP3llnVA96w23ND1nKH927X8L4lpHZL97NvUEhtOf40W6y7V8+VeaIliznxSWNH/vyK9U0SSL5E7BiknMi/c3X0sN50Bn0ihDS3mLOGcROwtBHoH7RDr1dl3Q8CvJ8TIhz6J25+waaYVpO8RZPNkjsI0OBMx2GVE2HD/dnUIf79idiDKqWm5Q5Ba/jrPwuzDza3mZm/fxc3wtxfRJQKfiJc/BL/Gk9xmfE0q43mqZ6QdpD8fQabzmRcZ/XMCHexlO5TFw3mwIJ3Nf9IOoLPRVD/1ZnXoj7SNmu8At3EIwcuOMSPCx0cfm1jnTg7qf7pQld8NsqGx+9cO12YcCHxnKA5lTmpGDuimbpiZjTr3+PGqGoA=
  on:
    tags: true
    repo: putdotio/pas-js
