language: node_js
node_js:
  - '12.13'
script:
  - npm run build
  - npm run coveralls
deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: altay.aydemir@gmail.com
  api_key:
    secure: s0bEAKaeDoCvya5XU8f6dHivlsq/GyamGz2fJaL6wM4KrNxId/CLbcUNBoHEqyb4wTXRn4BPCpfHsZim4b2zdFFWeL1hTtvOXE0OOi7P0Xqq6SanorqcyYuNJyrT8LsgnXCwAgiq68sWQbGm3kvZhFgjz4oR1wnKsabAh9bRj31D/WbaSJBgIxpcWEdsZZwbokZTVLjwu/up1hk49IjqSqyGvRKkOVd9TUg9O+JPMSLgATNx0LJpTw0IYbtzX7OsstN5UVaowPG/6ke8sEBQ+IsHHmARv7n4ahgbcR24hmYL4h8hb60LJVZ8JZ7th3S11h3DXs3xqH79cxXAySTYu54bI/84fScc253mbzXTiayJqKMkiRCopJKc2E7NrllCzhAvnc5kok2JqfpQ7i2pd6SLbswICb6Y/hOPzStJWwNYONC+4DogKTJUO48GY8Hk34ejZLez5TFgyQel/Dr8SZhfwKt7mDphWGx1sKPLrtltxeDyBYHX7kOYK1mpB54WXRtXVm6vJPfX2AnF1ZLDlYRirkJgn+9Hw8bBpBollFpEKLQmUKkmFbobTk1Jdpuy292US+tWb4j8T+/VJgjrbEf7FbsEnM/JYurO5H1vW7QUybmO+7w2djvo2/Ov7C9g6HKTc2uw6YNRNOTgIX07hq+2RJDjpG7ZgxRYF0NV9UE=
  on:
    tags: true
    repo: putdotio/pas-js
